--模型驱动
SELECT * FROM TM_EXPLORER;  --导航栏
SELECT * FROM TM_GRIDPAGE;  --通用查询页面
SELECT * FROM TM_ENTITYTEMPLATE;  --实体模板
SELECT * FROM TM_CRITERIASTATEMENT;  --查询语句
SELECT * FROM TM_COOLBAR;  --工具栏
SELECT * FROM TM_COOLBUTTON ;  --按钮
SELECT * FROM TM_COOLACTION ;  --事件
SELECT * FROM TM_COOLPERSPECTIVE ;  --布局
SELECT * FROM TM_COOLVIEW ;  --试图
SELECT * FROM TM_ATTRIBUTETEMPLATE; --条件和结果