
--添加用于存储字段的可见性,和枚举值
ALTER TABLE TM_SYSTEM_RUNNER_COND ADD OPTIONS VARCHAR2(2000);
--删除之前用于抓头的ID
ALTER TABLE tm_system_runner DROP COLUMN input_run_id;
--增加用于存储字段类型的字段
ALTER TABLE tm_system_runner_cond ADD FIELD_TYPE VARCHAR2(255);
--增加字段来判断该字段是否为索引字段
alter table TM_RUNNERATTR_SPECATTR add  isindex number;
--增加字段来标识该字段来自哪一个实体
alter table tm_system_runner_attr add spec_name varchar(255);

--添加规格查询页面
insert into tm_gridpage (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, CRITERIATEMPLATE_ID, CRITERIASTATEMENT_ID, RESULTTEMPLATE_ID, COOLBAR_ID, EXPORTCRITERIASTATEMENT_ID, STATISTICS, ASYNCHRONOUS, OTHERDATASOURCE, AUTOQUERY)
values (501, '实体规格管理', null, null, 1, sysdate, 'default', sysdate, 'default', 501, 501, 502, null, null, null, null, null, null);
--添加规格查询语句
insert into tm_criteriastatement (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, STATEMENTTYPE, CRITERIASTATEMENT, PREFEREDSTATEMENT, ROWMAPPERCLASS, SUFFIXSQLCRITERIA, DETAILTABLENAME)
values (501, '实体规格查询', null, null, 1, sysdate, 'default', sysdate, 'default', 2, 'select ID, NAME, CODE, PARENT_ID, (SELECT NAME FROM MM_ENTITY_SPEC WHERE T.PARENT_ID = ID) PARENT_NAME, SPEC_LEVEL_ID, (SELECT NAME FROM MM_DICTVALUE WHERE T.SPEC_LEVEL_ID = ID) SPEC_LEVEL_NAME, IS_VALID, (SELECT NAME FROM MM_DICTVALUE WHERE T.IS_VALID = ID) IS_VALID_NAME, MODEL_DOMAIN, (SELECT NAME FROM MM_DICTVALUE WHERE T.MODEL_DOMAIN = ID) MODEL_DOMAIN_NAME, NOTES, VERSION, CREATE_DATE, CREATOR_ID, MODIFY_DATE, MODIFIER_ID from (SELECT A.*, 0 PROJECT, null OPERATIONTYPE, null CHANGEINFO FROM MM_ENTITY_SPEC A ) T WHERE 1 = 1', null, null, null, null);
--添加查询模板和结果模板
insert into tm_entitytemplate (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ORDINAL, ENABLE)
values (501, '实体规格查询条件', null, null, 1, sysdate, 'default', sysdate, 'default', 1, 1);
insert into tm_entitytemplate (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ORDINAL, ENABLE)
values (502, '实体规格查询结果', null, null, 1, sysdate, 'default', sysdate, 'default', 1, 1);
--添加查询条件和结果映射
insert into tm_attributetemplate (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ENTITYTEMPLATE_ID, DEFAULTVALUE, NOTNULL, ORDINAL, CRITERIASQL, DATATYPE, DICTIONARYTYPE_ID, VISIBLE, COLUMNWIDTH, STATISTICSCOLUMN, CALCEXPRESSION, PRECISEQUERY, GROUPBYCOLUMN, ENUMERABLEMODELNAME, GRIDPAGE_ID)
values (5001, '名称', 'NAME', null, 1, sysdate, 'default', sysdate, 'default', 501, null, null, 1, null, 11, null, 1, null, null, null, null, null, null, null);
insert into tm_attributetemplate (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ENTITYTEMPLATE_ID, DEFAULTVALUE, NOTNULL, ORDINAL, CRITERIASQL, DATATYPE, DICTIONARYTYPE_ID, VISIBLE, COLUMNWIDTH, STATISTICSCOLUMN, CALCEXPRESSION, PRECISEQUERY, GROUPBYCOLUMN, ENUMERABLEMODELNAME, GRIDPAGE_ID)
values (5002, '编码', 'CODE', null, 1, sysdate, 'default', sysdate, 'default', 501, null, null, 2, null, 11, null, 1, null, null, null, null, null, null, null);
insert into tm_attributetemplate (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ENTITYTEMPLATE_ID, DEFAULTVALUE, NOTNULL, ORDINAL, CRITERIASQL, DATATYPE, DICTIONARYTYPE_ID, VISIBLE, COLUMNWIDTH, STATISTICSCOLUMN, CALCEXPRESSION, PRECISEQUERY, GROUPBYCOLUMN, ENUMERABLEMODELNAME, GRIDPAGE_ID)
values (5008, 'ID', 'ID', null, 1, sysdate, 'default', sysdate, 'default', 502, null, null, 1, null, 11, null, 1, null, null, null, null, null, null, null);
insert into tm_attributetemplate (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ENTITYTEMPLATE_ID, DEFAULTVALUE, NOTNULL, ORDINAL, CRITERIASQL, DATATYPE, DICTIONARYTYPE_ID, VISIBLE, COLUMNWIDTH, STATISTICSCOLUMN, CALCEXPRESSION, PRECISEQUERY, GROUPBYCOLUMN, ENUMERABLEMODELNAME, GRIDPAGE_ID)
values (5009, '名称', 'NAME', null, 1, sysdate, 'default', sysdate, 'default', 502, null, null, 2, null, 11, null, 1, null, null, null, null, null, null, null);
insert into tm_attributetemplate (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ENTITYTEMPLATE_ID, DEFAULTVALUE, NOTNULL, ORDINAL, CRITERIASQL, DATATYPE, DICTIONARYTYPE_ID, VISIBLE, COLUMNWIDTH, STATISTICSCOLUMN, CALCEXPRESSION, PRECISEQUERY, GROUPBYCOLUMN, ENUMERABLEMODELNAME, GRIDPAGE_ID)
values (5010, '编码', 'CODE', null, 1, sysdate, 'default', sysdate, 'default', 502, null, null, 3, null, 11, null, 1, null, null, null, null, null, null, null);
insert into tm_attributetemplate (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ENTITYTEMPLATE_ID, DEFAULTVALUE, NOTNULL, ORDINAL, CRITERIASQL, DATATYPE, DICTIONARYTYPE_ID, VISIBLE, COLUMNWIDTH, STATISTICSCOLUMN, CALCEXPRESSION, PRECISEQUERY, GROUPBYCOLUMN, ENUMERABLEMODELNAME, GRIDPAGE_ID)
values (5011, '父实体', 'PARENT_NAME', null, 1, sysdate, 'default', sysdate, 'default', 502, null, null, 4, null, 11, null, 1, null, null, null, null, null, null, null);
insert into tm_attributetemplate (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ENTITYTEMPLATE_ID, DEFAULTVALUE, NOTNULL, ORDINAL, CRITERIASQL, DATATYPE, DICTIONARYTYPE_ID, VISIBLE, COLUMNWIDTH, STATISTICSCOLUMN, CALCEXPRESSION, PRECISEQUERY, GROUPBYCOLUMN, ENUMERABLEMODELNAME, GRIDPAGE_ID)
values (5012, '规格层级', 'SPEC_LEVEL_NAME', null, 1, sysdate, 'default', sysdate, 'default', 502, null, null, 5, null, 11, null, 1, null, null, null, null, null, null, null);
insert into tm_attributetemplate (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ENTITYTEMPLATE_ID, DEFAULTVALUE, NOTNULL, ORDINAL, CRITERIASQL, DATATYPE, DICTIONARYTYPE_ID, VISIBLE, COLUMNWIDTH, STATISTICSCOLUMN, CALCEXPRESSION, PRECISEQUERY, GROUPBYCOLUMN, ENUMERABLEMODELNAME, GRIDPAGE_ID)
values (5013, '业务域', 'MODEL_DOMAIN_NAME', null, 1, sysdate, 'default', sysdate, 'default', 502, null, null, 6, null, 11, null, 1, null, null, null, null, null, null, null);
insert into tm_attributetemplate (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ENTITYTEMPLATE_ID, DEFAULTVALUE, NOTNULL, ORDINAL, CRITERIASQL, DATATYPE, DICTIONARYTYPE_ID, VISIBLE, COLUMNWIDTH, STATISTICSCOLUMN, CALCEXPRESSION, PRECISEQUERY, GROUPBYCOLUMN, ENUMERABLEMODELNAME, GRIDPAGE_ID)
values (5014, '有效性', 'IS_VALID_NAME', null, 1, sysdate, 'default', sysdate, 'default', 502, null, null, 7, null, 11, null, 1, null, null, null, null, null, null, null);
insert into tm_attributetemplate (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ENTITYTEMPLATE_ID, DEFAULTVALUE, NOTNULL, ORDINAL, CRITERIASQL, DATATYPE, DICTIONARYTYPE_ID, VISIBLE, COLUMNWIDTH, STATISTICSCOLUMN, CALCEXPRESSION, PRECISEQUERY, GROUPBYCOLUMN, ENUMERABLEMODELNAME, GRIDPAGE_ID)
values (5015, '作用范围', 'USE_SCOPE_NAME', null, 1, sysdate, 'default', sysdate, 'default', 502, null, null, 8, null, 11, null, 1, null, null, null, null, null, null, null);
insert into tm_attributetemplate (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ENTITYTEMPLATE_ID, DEFAULTVALUE, NOTNULL, ORDINAL, CRITERIASQL, DATATYPE, DICTIONARYTYPE_ID, VISIBLE, COLUMNWIDTH, STATISTICSCOLUMN, CALCEXPRESSION, PRECISEQUERY, GROUPBYCOLUMN, ENUMERABLEMODELNAME, GRIDPAGE_ID)
values (5016, '创建日期', 'CREATE_DATE', null, 1, sysdate, 'default', sysdate, 'default', 502, null, null, 9, null, 11, null, 1, null, null, null, null, null, null, null);
insert into tm_attributetemplate (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ENTITYTEMPLATE_ID, DEFAULTVALUE, NOTNULL, ORDINAL, CRITERIASQL, DATATYPE, DICTIONARYTYPE_ID, VISIBLE, COLUMNWIDTH, STATISTICSCOLUMN, CALCEXPRESSION, PRECISEQUERY, GROUPBYCOLUMN, ENUMERABLEMODELNAME, GRIDPAGE_ID)
values (5017, '创建人', 'CREATOR_ID', null, 1, sysdate, 'default', sysdate, 'default', 502, null, null, 10, null, 11, null, 1, null, null, null, null, null, null, null);
insert into tm_attributetemplate (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ENTITYTEMPLATE_ID, DEFAULTVALUE, NOTNULL, ORDINAL, CRITERIASQL, DATATYPE, DICTIONARYTYPE_ID, VISIBLE, COLUMNWIDTH, STATISTICSCOLUMN, CALCEXPRESSION, PRECISEQUERY, GROUPBYCOLUMN, ENUMERABLEMODELNAME, GRIDPAGE_ID)
values (5018, '修改日期', 'MODIFY_DATE', null, 1, sysdate, 'default', sysdate, 'default', 502, null, null, 11, null, 11, null, 1, null, null, null, null, null, null, null);
insert into tm_attributetemplate (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ENTITYTEMPLATE_ID, DEFAULTVALUE, NOTNULL, ORDINAL, CRITERIASQL, DATATYPE, DICTIONARYTYPE_ID, VISIBLE, COLUMNWIDTH, STATISTICSCOLUMN, CALCEXPRESSION, PRECISEQUERY, GROUPBYCOLUMN, ENUMERABLEMODELNAME, GRIDPAGE_ID)
values (5019, '修改人', 'MODIFIER_ID', null, 1, sysdate, 'default', sysdate, 'default', 502, null, null, 12, null, 11, null, 1, null, null, null, null, null, null, null);
insert into tm_attributetemplate (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ENTITYTEMPLATE_ID, DEFAULTVALUE, NOTNULL, ORDINAL, CRITERIASQL, DATATYPE, DICTIONARYTYPE_ID, VISIBLE, COLUMNWIDTH, STATISTICSCOLUMN, CALCEXPRESSION, PRECISEQUERY, GROUPBYCOLUMN, ENUMERABLEMODELNAME, GRIDPAGE_ID)
values (5020, '备注', 'NOTES', null, 1, sysdate, 'default', sysdate, 'default', 502, null, null, 13, null, 11, null, 1, null, null, null, null, null, null, null);






