--添加页面总线存储序列
CREATE SEQUENCE SEQ_TM_PAGEBUS MINVALUE 1 MAXVALUE 999999999999999 START WITH 1 INCREMENT BY 1;
--添加页面总线数据存储表
CREATE TABLE "TM_PAGEBUS" 
	("ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(255), 
	"CODE" VARCHAR2(255), 
	"VERSION" NUMBER NOT NULL ENABLE, 
	"HEAD_URL" VARCHAR2(255),
	"LAST_URL" VARCHAR2(255)
   );
--在场景中添加一列用来保存所使用的url
ALTER TABLE TM_SYSTEM_RUNNER ADD SYSDATESTR NUMBER;
--添加页面总线服务导航栏
INSERT INTO TM_EXPLORER (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, PARENTEXPLORER_ID, ORDINAL, GRIDPAGE_ID, EXPANDACTION_ID, PAGINATED, ICON, ENABLE) 
VALUES (1200, '页面总线服务', NULL, NULL, 1, SYSDATE, 'DEFAULT', SYSDATE, 'DEFAULT', 983, 4, 500, NULL, NULL, NULL, 1);
--添加页面总线服务的通用查询界面
INSERT INTO TM_GRIDPAGE (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, CRITERIATEMPLATE_ID, CRITERIASTATEMENT_ID, RESULTTEMPLATE_ID, COOLBAR_ID, EXPORTCRITERIASTATEMENT_ID, STATISTICS, ASYNCHRONOUS, OTHERDATASOURCE, AUTOQUERY)
VALUES (500, '页面总线服务器', NULL, NULL, 1,SYSDATE, 'DEFAULT',SYSDATE, 'DEFAULT', null, 480, 502, 30, NULL, NULL, NULL, NULL, NULL);
--添加页面总线查询服务模板
INSERT INTO TM_ENTITYTEMPLATE (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ORDINAL, ENABLE)
VALUES (502, '页面总线服务结果', NULL, NULL, 1, SYSDATE, 'DEFAULT',SYSDATE, 'DEFAULT', 1, 1);
--添加页面总线通用查询的工具栏
INSERT INTO TM_COOLBAR (ID, NAME, CODE, VERSION, ENABLE)
VALUES (30, '页面总线', 'PAGEBUS', 1, 1);
--添加查询语句
INSERT INTO TM_CRITERIASTATEMENT (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, STATEMENTTYPE, CRITERIASTATEMENT, PREFEREDSTATEMENT, ROWMAPPERCLASS, SUFFIXSQLCRITERIA, DETAILTABLENAME) 
VALUES (480, '页面总线服务', NULL, NULL, 1, SYSDATE, 'admin', SYSDATE, 'admin', 2, 'SELECT ID,NAME,CODE,VERSION,HEAD_URL,LAST_URL FROM TM_PAGEBUS WHERE 1=1', NULL, NULL, NULL, NULL);
--添加结果映射
INSERT INTO TM_ATTRIBUTETEMPLATE (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ENTITYTEMPLATE_ID, DEFAULTVALUE, NOTNULL, ORDINAL, CRITERIASQL, DATATYPE, DICTIONARYTYPE_ID, VISIBLE, COLUMNWIDTH, STATISTICSCOLUMN, CALCEXPRESSION, PRECISEQUERY, GROUPBYCOLUMN, ENUMERABLEMODELNAME, GRIDPAGE_ID)
VALUES (4201, 'ID', 'ID', NULL, 1, SYSDATE, 'DEFAULT', SYSDATE, 'DEFAULT', 502, NULL, NULL, 1, NULL, 11, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 500);
INSERT INTO TM_ATTRIBUTETEMPLATE (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ENTITYTEMPLATE_ID, DEFAULTVALUE, NOTNULL, ORDINAL, CRITERIASQL, DATATYPE, DICTIONARYTYPE_ID, VISIBLE, COLUMNWIDTH, STATISTICSCOLUMN, CALCEXPRESSION, PRECISEQUERY, GROUPBYCOLUMN, ENUMERABLEMODELNAME, GRIDPAGE_ID)
VALUES (4202, '编码', 'CODE', NULL, 1, SYSDATE, 'DEFAULT', SYSDATE, 'DEFAULT', 502, NULL, NULL, 2, NULL, 11, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 500);
INSERT INTO TM_ATTRIBUTETEMPLATE (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ENTITYTEMPLATE_ID, DEFAULTVALUE, NOTNULL, ORDINAL, CRITERIASQL, DATATYPE, DICTIONARYTYPE_ID, VISIBLE, COLUMNWIDTH, STATISTICSCOLUMN, CALCEXPRESSION, PRECISEQUERY, GROUPBYCOLUMN, ENUMERABLEMODELNAME, GRIDPAGE_ID)
VALUES (4203, '名称', 'NAME', NULL, 1, SYSDATE, 'DEFAULT', SYSDATE, 'DEFAULT', 502, NULL, NULL, 3, NULL, 11, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 500);
INSERT INTO TM_ATTRIBUTETEMPLATE (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ENTITYTEMPLATE_ID, DEFAULTVALUE, NOTNULL, ORDINAL, CRITERIASQL, DATATYPE, DICTIONARYTYPE_ID, VISIBLE, COLUMNWIDTH, STATISTICSCOLUMN, CALCEXPRESSION, PRECISEQUERY, GROUPBYCOLUMN, ENUMERABLEMODELNAME, GRIDPAGE_ID)
VALUES (4204, '请求URL', 'HEAD_URL', NULL, 1, SYSDATE, 'DEFAULT', SYSDATE, 'DEFAULT', 502, NULL, NULL, 4, NULL, 11, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 500);
INSERT INTO TM_ATTRIBUTETEMPLATE (ID, NAME, CODE, MEMO, VERSION, CREATEDATE, CREATOR, UPDATEDATE, UPDATER, ENTITYTEMPLATE_ID, DEFAULTVALUE, NOTNULL, ORDINAL, CRITERIASQL, DATATYPE, DICTIONARYTYPE_ID, VISIBLE, COLUMNWIDTH, STATISTICSCOLUMN, CALCEXPRESSION, PRECISEQUERY, GROUPBYCOLUMN, ENUMERABLEMODELNAME, GRIDPAGE_ID)
VALUES (4205, '回应URL', 'LAST_URL', NULL, 1, SYSDATE, 'DEFAULT', SYSDATE, 'DEFAULT', 502, NULL, NULL, 5, NULL, 11, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 500);


--添加用于存储字段的可见性,和枚举值
--ALTER TABLE TM_SYSTEM_RUNNER_COND ADD ENABLE NUMBER(1);
ALTER TABLE TM_SYSTEM_RUNNER_COND ADD OPTIONS VARCHAR2(2000);







